mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl #关闭打印
  global-config:
    db-config:
      id-type: ASSIGN_ID
server:
  port: 16052
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sosd_szcp_database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver